Add must_use to rerandomise methods
eleanor-em/rust-elgamal pull request #2
Opened 2024-06-20 15:20 UTC by tcerqueira

I think if one calls a rerandomise function and ignores the returned ciphertext, it is likely a bug. This attribute macro warns if the the return value is unused.

Yes, I did this mistake 🥲

2024-06-20 17:17 UTC, eleanor-em requested changes

2024-06-20 17:17 UTC, eleanor-em commented on src/encrypt.rs
> +    #[must_use = "the Ciphertext input it's not mutated, the function returns the new rerandomised Ciphertext"]
This is a great idea, thank you very muchh! While I am not maintaining this repository any more, we might as well merge this. Just a small grammar note: please replace `it's` with `is`.

2024-06-21 10:36 UTC, tcerqueira commented
Hold on, my rustfmt changed the order of the imports

2024-06-21 17:30 UTC, merged

2024-06-21 17:30 UTC, eleanor-em commented
Great, thanks very much!